
drop TABLE DATA_JOBS;
create table DATA_JOBS
(JOB_ID			 SERIAL PRIMARY KEY,
 JOB_CATEGORY	VARCHAR	NOT NULL,
 JOB_TITLE		VARCHAR NOT NULL,
 SALARY_ESTIMATE	VARCHAR NOT NULL,
 JOB_DESCRIPTION	VARCHAR,
 RATING			FLOAT,
 COMPANY_NAME		VARCHAR,
 LOCATION			VARCHAR,
 HEADQUARTERS		VARCHAR,
 SIZE				VARCHAR,
 FOUNDED			INT,
 TYPE_OF_OWNERSHIP	VARCHAR,
 INDUSTRY           VARCHAR,
 SECTOR				VARCHAR,
 REVENUE			VARCHAR,
 COMPETITORS		VARCHAR,
 EASY_APPLY			VARCHAR
);
